name = "go-urls"
main = "src/index.ts"
compatibility_date = "2023-01-01"

kv_namespaces = [
  { binding = "GO_URLS", id = "6ec3404005ee4537bcb35a7660c4f93c", preview_id = "6ec3404005ee4537bcb35a7660c4f93c" }
]

